### ISSUE TITLE
Changes Required!

### ISSUE THREAD

**Issue by VishwaS-22** [Sakthi511/Sakthi511#1]
Hey @Sakthi511! In your profile the marked part should be in proper order, Please update.

![SMARepo](https://user-images.githubusercontent.com/85573504/226154853-f537c0f9-ae60-45a1-9444-9bd2765802c8.png)

**Comment by Meenakshi-here** [comment]
Thank You! Sure I will work on it!

**Comment by Meenakshi-here** [comment]
Changes have been made!
Thank You!

**Comment by VishwaS-22** [comment]
Hey @Sakthi511! Now it LGTM, Happy to collaborate with you in future projects. Looking forward to learn a lot from you. Happy Learning.

**Comment by Meenakshi-here** [comment]
Same here!
